### ISSUE TITLE
I got a ModuleManager kspe error

### ISSUE THREAD

**Issue by Drake20008** [KSP-ModularManagement/KSPe#73]
Hi @Lisias so when i pressed closed it said that you may be able to help me fix this error this is the page i got.
![error](https://github.com/KSP-ModularManagement/KSPe/assets/168310254/6128481d-611b-4680-9834-ea22f014a0ab)

**Comment by Lisias** [comment]
Hi, @Drake20008 . 

Please drag and drop here the `KSP.log' file so I can check what's happening. These messages just tell you threre's something wrong, what's wrong can only be found on the `KSP.log`.

(rememeber to exit KSP before copying the log, or the file may be truncated, removing some information that may be necessary)

**Comment by Drake20008** [comment]
[CHANGE_LOG.md](https://github.com/KSP-ModularManagement/KSPe/files/15172057/CHANGE_LOG.md)
Alr is this it

**Comment by Lisias** [comment]
> [CHANGE_LOG.md](https://github.com/KSP-ModularManagement/KSPe/files/15172057/CHANGE_LOG.md) Alr is this it

No. The `KSP.log` is a file called, well, `KSP.log`. You will find instructions about where to find it here:

https://forum.kerbalspaceprogram.com/topic/83212-how-to-get-support-read-first/

**Comment by Drake20008** [comment]
[KSP.log](https://github.com/KSP-ModularManagement/KSPe/files/15182100/KSP.log)
alr i hope this is it if it isn't I'm sorry I'm relatively new to this XD

**Comment by Lisias** [comment]
@Drake20008 , got it. You using Steam and I'm betting you are using the Steam Launcher stunt to get rid of the launcher, right?

This is the problem: that stunt I think you are using **SCREWS THINGS UP**. The PD-Launcher, to be launched, changed a thingy called CWD (Current Working Directory), and by doing the stunt KSP will get lost and start to save some files on the wrong place.

KSPe will follow suit, in special the `Install Checker` that, in reality, were made focusing on CurseForge users - and I completely forgot about this crappy stunt on the Steam Launcher.

If I'm right and you are using the stunt, please undo the stunt, reinstall everything, and come back to me and I will teach you a safer way to get rid of that crap.

I'm sorry KSPe screwed up for you, but... Speaking frankly, better now then later - running KSP with the wrong CWD will make it behave weirdlly, saving files on the wrong place at very best, and missing files at very worst - essentially, what made KSPe to bork.

**Comment by Drake20008** [comment]
Im not actually doing anything to the steam launcher when i press play it opens private divisions and then i press play there if that is the problem tell me what to undo

**Comment by Lisias** [comment]
@Drake20008 my apologies!! I jumped into conclusions, I didn't paid the proper attention when analyzing your `KSP.log` - by plain "luck", I had just diagnosed another fellow Kerbonaut rig that had this problem and ended up jumping into conclusions.

I found the real issue: you have a `GameData` inside your `GameData`!!

```
[LOG 16:10:25.495] AssemblyLoader: Loading assembly at C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\GameData\000_KSPe.dll
                                                                                                                          ^^^^^ HERE ! ^^^^^
```

Move everything inside `GameData\GameData` to `GameData` itself. Then delete the `GameData\GameData` directory (and only it, leave the parent `GameData` alone!)

**Comment by Drake20008** [comment]
alr ty it worked

**Comment by Lisias** [comment]
Thanks for closing it! I forgot to do it!!! 😸
